"use client";

import {
  EligibilityStatusBadge,
  MatchStatusBadge,
  SkillChip,
} from "@/components/companies/MatchBadges";
import { HRDecisionBadge } from "@/components/sharing/SharingBadges";
import {
  ReadinessStatusBadge,
  RiskBadge,
  ScoreMeter,
} from "@/components/readiness/ReadinessBadges";
import { RESUME_REVIEW_STATUS_LABELS } from "@/lib/resume-constants";
import { HR_DECISION_LABELS } from "@/lib/sharing-constants";
import {
  PROFICIENCY_LABELS,
  VERIFICATION_STATUS_LABELS,
} from "@/lib/tech-constants";
import { formatDate, formatScore } from "@/lib/utils";
import type { PublicBrandingSettings } from "@/types/branding";
import type { PlacementPassportView } from "@/types/passport";
import type { ProficiencyLevel, VerificationStatus } from "@/types/tech-stack";
import { Award, BookOpen, Briefcase, FileText, Gauge, Network, Sparkles } from "lucide-react";

interface PlacementPassportDocumentProps {
  passport: PlacementPassportView;
  branding: PublicBrandingSettings;
}

export function PlacementPassportDocument({
  passport,
  branding,
}: PlacementPassportDocumentProps) {
  const { summary } = passport;
  const { student, readiness, company, roleInterests, hr } = summary;

  return (
    <article className="passport-document mx-auto max-w-4xl space-y-6 rounded-2xl border border-surface-border bg-white p-8 shadow-card print:max-w-none print:rounded-none print:border-0 print:p-0 print:shadow-none">
      <header className="border-b border-surface-border pb-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-600">
              {branding.institutionName} · {branding.placementCellName}
            </p>
            <p className="mt-1 text-[10px] text-slate-400">
              Placement Passport · Generated by {branding.productName}
            </p>
            <h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">
              {student.fullName}
            </h1>
            <p className="mt-1 text-sm text-slate-500">
              {student.rollNumber} · {student.branch} · Batch {student.batch}
            </p>
            {company && (
              <p className="mt-2 text-sm font-medium text-slate-700">
                {company.companyName} · {company.roleTitle}
              </p>
            )}
          </div>
          <div className="text-right text-sm text-slate-500">
            <p>Generated {formatDate(passport.generatedAt)}</p>
            <p className="mt-1">By {passport.generatedByName}</p>
          </div>
        </div>
      </header>

      <section className="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
        <div className="rounded-xl border border-surface-border p-5">
          <div className="mb-4 flex items-center gap-2">
            <Gauge className="h-4 w-4 text-brand-600" />
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
              Readiness Summary
            </h2>
          </div>
          <div className="flex flex-wrap items-end gap-4">
            <div>
              <p className="text-4xl font-semibold text-slate-900">
                {formatScore(readiness.overallScore)}
              </p>
              <p className="text-xs text-slate-500">Overall readiness</p>
            </div>
            <ReadinessStatusBadge status={readiness.readinessStatus} />
            <RiskBadge level={readiness.riskLevel} />
          </div>
          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            <ScoreMeter score={readiness.technicalReadiness} label="Technical" />
            <ScoreMeter
              score={readiness.communicationReadiness}
              label="Communication"
            />
            <ScoreMeter score={readiness.resumeReadiness} label="Resume" />
            <ScoreMeter score={readiness.techStackReadiness} label="Tech Stack" />
            <ScoreMeter score={readiness.profileReadiness} label="Profile" />
            <ScoreMeter score={readiness.academicReadiness} label="Academic" />
          </div>
        </div>

        <div className="rounded-xl border border-surface-border p-5">
          <div className="mb-4 flex items-center gap-2">
            <BookOpen className="h-4 w-4 text-brand-600" />
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
              Academic Summary
            </h2>
          </div>
          <dl className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <dt className="text-slate-500">CGPA</dt>
              <dd className="font-semibold text-slate-900">
                {passport.academic.cgpa != null
                  ? passport.academic.cgpa.toFixed(2)
                  : "—"}
              </dd>
            </div>
            <div>
              <dt className="text-slate-500">Active Backlogs</dt>
              <dd className="font-semibold text-slate-900">
                {passport.academic.activeBacklogs}
              </dd>
            </div>
            <div>
              <dt className="text-slate-500">Graduation Year</dt>
              <dd className="font-semibold text-slate-900">
                {passport.academic.graduationYear}
              </dd>
            </div>
            <div>
              <dt className="text-slate-500">Branch / Batch</dt>
              <dd className="font-semibold text-slate-900">
                {passport.academic.branch} · {passport.academic.batch}
              </dd>
            </div>
          </dl>
          {roleInterests.length > 0 && (
            <div className="mt-4 border-t border-surface-border pt-4">
              <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
                Role Interests
              </p>
              <div className="mt-2 flex flex-wrap gap-2">
                {roleInterests.map((role) => (
                  <span
                    key={role}
                    className="rounded-full bg-slate-100 px-2.5 py-0.5 text-xs font-medium text-slate-700"
                  >
                    {role}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </section>

      {company && (
        <section className="rounded-xl border border-surface-border p-5">
          <div className="mb-4 flex items-center gap-2">
            <Briefcase className="h-4 w-4 text-brand-600" />
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
              Company Fit Summary
            </h2>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <span className="text-2xl font-semibold text-slate-900">
              {formatScore(company.matchScore)}
            </span>
            <MatchStatusBadge status={company.matchStatus} />
            <EligibilityStatusBadge status={company.eligibilityStatus} />
          </div>
          <div className="mt-4 grid gap-4 md:grid-cols-3">
            <div>
              <p className="mb-2 text-xs font-medium uppercase text-slate-500">
                Matched Skills
              </p>
              <div className="flex flex-wrap gap-1.5">
                {company.matchedSkills.length === 0 ? (
                  <span className="text-sm text-slate-500">None recorded</span>
                ) : (
                  company.matchedSkills.map((s) => (
                    <SkillChip key={s} label={s} variant="matched" />
                  ))
                )}
              </div>
            </div>
            <div>
              <p className="mb-2 text-xs font-medium uppercase text-slate-500">
                Missing Skills
              </p>
              <div className="flex flex-wrap gap-1.5">
                {company.missingSkills.length === 0 ? (
                  <span className="text-sm text-slate-500">None identified</span>
                ) : (
                  company.missingSkills.map((s) => (
                    <SkillChip key={s} label={s} variant="missing" />
                  ))
                )}
              </div>
            </div>
            <div>
              <p className="mb-2 text-xs font-medium uppercase text-slate-500">
                Fit Risks
              </p>
              <div className="flex flex-wrap gap-1.5">
                {company.risks.length === 0 ? (
                  <span className="text-sm text-slate-500">No major risks</span>
                ) : (
                  company.risks.map((r) => (
                    <SkillChip key={r} label={r} variant="risk" />
                  ))
                )}
              </div>
            </div>
          </div>
        </section>
      )}

      <section className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border border-surface-border p-5">
          <div className="mb-4 flex items-center gap-2">
            <Award className="h-4 w-4 text-brand-600" />
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
              Verified Skills
            </h2>
          </div>
          {passport.skills.length === 0 ? (
            <p className="text-sm text-slate-500">No skills recorded yet.</p>
          ) : (
            <div className="space-y-3">
              {passport.skills.map((skill) => (
                <div
                  key={`${skill.name}-${skill.category}`}
                  className="flex flex-wrap items-center justify-between gap-2 border-b border-surface-border pb-3 last:border-0 last:pb-0"
                >
                  <div>
                    <p className="font-medium text-slate-900">{skill.name}</p>
                    <p className="text-xs text-slate-500">
                      {skill.category}
                      {skill.evidenceSource
                        ? ` · ${skill.evidenceSource}`
                        : ""}
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2 text-xs">
                    <span className="rounded-full bg-slate-100 px-2 py-0.5 font-medium text-slate-700">
                      {PROFICIENCY_LABELS[skill.proficiencyLevel as ProficiencyLevel] ??
                        skill.proficiencyLevel}
                    </span>
                    <span className="rounded-full bg-brand-50 px-2 py-0.5 font-medium text-brand-700">
                      {VERIFICATION_STATUS_LABELS[
                        skill.verificationStatus as VerificationStatus
                      ] ?? skill.verificationStatus}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="rounded-xl border border-surface-border p-5">
          <div className="mb-4 flex items-center gap-2">
            <FileText className="h-4 w-4 text-brand-600" />
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
              Resume Summary
            </h2>
          </div>
          {!passport.resume ? (
            <p className="text-sm text-slate-500">No active resume on file.</p>
          ) : (
            <dl className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <dt className="text-slate-500">Review Status</dt>
                <dd className="font-medium text-slate-900">
                  {RESUME_REVIEW_STATUS_LABELS[
                    passport.resume.reviewStatus as keyof typeof RESUME_REVIEW_STATUS_LABELS
                  ] ?? passport.resume.reviewStatus}
                </dd>
              </div>
              <div>
                <dt className="text-slate-500">Resume Score</dt>
                <dd className="font-medium text-slate-900">
                  {formatScore(passport.resume.resumeScore)}
                </dd>
              </div>
              {[
                ["ATS Friendly", passport.resume.atsFriendly],
                ["LinkedIn", passport.resume.hasLinkedIn],
                ["GitHub", passport.resume.hasGitHub],
                ["Projects", passport.resume.hasProjects],
                ["Certifications", passport.resume.hasCertifications],
              ].map(([label, value]) => (
                <div key={String(label)}>
                  <dt className="text-slate-500">{label}</dt>
                  <dd className="font-medium text-slate-900">
                    {value ? "Yes" : "No"}
                  </dd>
                </div>
              ))}
            </dl>
          )}
        </div>
      </section>

      {passport.evidence && (
        <section className="rounded-xl border border-surface-border p-5">
          <div className="mb-4 flex items-center gap-2">
            <Network className="h-4 w-4 text-brand-600" />
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
              Skill Evidence
            </h2>
          </div>
          <div className="grid gap-4 sm:grid-cols-3">
            <EvidenceList
              title="Top Verified"
              items={passport.evidence.topVerifiedSkills}
            />
            <EvidenceList
              title="Strong Evidence"
              items={passport.evidence.strongEvidenceSkills}
            />
            <EvidenceList
              title="Needs Proof"
              items={passport.evidence.skillsNeedingProof}
            />
          </div>
          {passport.evidence.companyFitEvidence && (
            <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm">
              <p className="font-medium text-slate-800">
                Company fit — {passport.evidence.companyFitEvidence.roleTitle}
              </p>
              {passport.evidence.companyFitEvidence.verifiedMatching.length > 0 && (
                <p className="mt-1 text-slate-600">
                  Verified match:{" "}
                  {passport.evidence.companyFitEvidence.verifiedMatching.join(", ")}
                </p>
              )}
              {passport.evidence.companyFitEvidence.missingRequired.length > 0 && (
                <p className="mt-1 text-amber-700">
                  Missing required:{" "}
                  {passport.evidence.companyFitEvidence.missingRequired.join(", ")}
                </p>
              )}
            </div>
          )}
        </section>
      )}

      <section className="rounded-xl border border-surface-border p-5">
        <div className="mb-4 flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-brand-600" />
          <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
            Strengths & Risks
          </h2>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          <div>
            <p className="mb-2 text-xs font-medium uppercase text-emerald-700">
              Strengths
            </p>
            <div className="flex flex-wrap gap-2">
              {passport.strengths.length === 0 ? (
                <span className="text-sm text-slate-500">—</span>
              ) : (
                passport.strengths.map((s) => (
                  <span
                    key={s}
                    className="rounded-full bg-emerald-50 px-2.5 py-0.5 text-xs font-medium text-emerald-800"
                  >
                    {s}
                  </span>
                ))
              )}
            </div>
          </div>
          <div>
            <p className="mb-2 text-xs font-medium uppercase text-amber-700">
              Risks
            </p>
            <div className="flex flex-wrap gap-2">
              {passport.risks.length === 0 ? (
                <span className="text-sm text-slate-500">—</span>
              ) : (
                passport.risks.map((r) => (
                  <span
                    key={r}
                    className="rounded-full bg-amber-50 px-2.5 py-0.5 text-xs font-medium text-amber-800"
                  >
                    {r}
                  </span>
                ))
              )}
            </div>
          </div>
        </div>
        <div className="mt-4 rounded-lg bg-brand-50/60 p-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-brand-700">
            TPO Recommendation
          </p>
          <p className="mt-1 text-sm text-slate-700">
            {passport.recommendations.nextRecommendedAction}
          </p>
        </div>
      </section>

      {passport.showHrBlock && hr && (
        <section className="rounded-xl border border-surface-border p-5">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">
            HR Review
          </h2>
          <div className="mt-3 flex flex-wrap items-center gap-3">
            <HRDecisionBadge decision={hr.hrDecision} />
            <span className="text-sm text-slate-500">
              Shared {formatDate(new Date(hr.sharedAt))}
            </span>
          </div>
          {hr.hrComments && (
            <p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">
              {hr.hrComments}
            </p>
          )}
        </section>
      )}

      <footer className="border-t border-surface-border pt-4 text-center text-xs text-slate-400 print:pt-6">
        {branding.institutionName} · {branding.placementCellName} ·{" "}
        {branding.productName} Placement Passport · Snapshot generated{" "}
        {formatDate(passport.generatedAt)} · Confidential placement intelligence
      </footer>
    </article>
  );
}

function EvidenceList({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <p className="text-xs font-medium uppercase text-slate-500">{title}</p>
      {items.length === 0 ? (
        <p className="mt-1 text-sm text-slate-400">—</p>
      ) : (
        <ul className="mt-1 space-y-0.5 text-sm text-slate-800">
          {items.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      )}
    </div>
  );
}
