import type { PublicBrandingSettings } from "@/types/branding";

interface ReportFooterProps {
  branding: PublicBrandingSettings;
}

export function ReportFooter({ branding }: ReportFooterProps) {
  return (
    <footer className="report-print-footer mt-10 border-t border-slate-200 pt-4">
      {branding.reportSignatureName && (
        <div className="mb-4 text-sm">
          <p className="font-semibold text-slate-800">
            {branding.reportSignatureName}
          </p>
          {branding.reportSignatureDesignation && (
            <p className="text-slate-600">
              {branding.reportSignatureDesignation}
            </p>
          )}
        </div>
      )}
      <div className="text-center text-[10px] text-slate-500">
        <p className="font-medium text-slate-600">
          {branding.reportFooterText ??
            `Generated by ${branding.productName} — ${branding.tagline}`}
        </p>
        <p className="mt-0.5">
          {branding.institutionName}
          {branding.contactEmail ? ` · ${branding.contactEmail}` : ""}
          {branding.contactPhone ? ` · ${branding.contactPhone}` : ""}
        </p>
        <p className="mt-0.5">
          Confidential — For internal placement review and management use
        </p>
      </div>
    </footer>
  );
}
